#!/usr/bin/env bash
# bash script generated by claude ai and was used as tooling
# gen_aes_vectors.sh
# Compiles aes_ref.c, generates 100 AES-128 test vectors using /dev/urandom,
# and writes them to aes_test_vectors.csv
#
# Expected C program interface:
#   ./aes_ref <key_hex> <plaintext_hex>
#   stdout: <ciphertext_hex>   (32 hex chars, no prefix)
#
# Key and plaintext format (matching FIPS 197 / your existing convention):
#   16 bytes = 32 hex chars, underscore-separated every 4 bytes
#   e.g. 2b7e1516_28aed2a6_abf71588_09cf4f3c

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
SRC="aes_ref.c"
BIN="./aes_ref"
NUM_VECTORS=1999
# 1999 generated vector + first nist vector
OUTFILE="aes_test_vectors_enc.csv"

# ── Compile ───────────────────────────────────────────────────────────────────
echo "[1/3] Compiling $SRC ..."
gcc -O2 -Wall -o "$BIN" "$SRC"
echo "Compiled OK"
echo "---"

# ── Helper: read N random bytes from /dev/urandom, output as hex ──────────────
# Usage: random_hex <num_bytes>
random_hex() {
    dd if=/dev/urandom bs=1 count="$1" 2>/dev/null | xxd -p | tr -d '\n'
}

# Helper: insert underscores every 8 hex chars (= every 4 bytes)
# 2b7e151628aed2a6abf7158809cf4f3c  ->  2b7e1516_28aed2a6_abf71588_09cf4f3c
format_hex() {
    local h="$1"
    echo "${h:0:8}_${h:8:8}_${h:16:8}_${h:24:8}"
}

# ── Generate vectors ──────────────────────────────────────────────────────────
echo "[2/3] Generating $NUM_VECTORS test vectors ..."

# Write CSV header
echo "key,plaintext,ciphertext" > "$OUTFILE"

# Always include the FIPS 197 Appendix B known-answer vector first
KNOWN_KEY="2b7e1516_28aed2a6_abf71588_09cf4f3c"
KNOWN_PLAIN="3243f6a8_885a308d_313198a2_e0370734"
KNOWN_KEY_RAW="2b7e151628aed2a6abf7158809cf4f3c"
KNOWN_PLAIN_RAW="3243f6a8885a308d313198a2e0370734"
KNOWN_CIPHER=$("$BIN" enc "$KNOWN_PLAIN" "$KNOWN_KEY")
echo "${KNOWN_KEY_RAW},${KNOWN_PLAIN_RAW},${KNOWN_CIPHER}" >> "$OUTFILE"

# Generate remaining (NUM_VECTORS - 1) random vectors
for i in $(seq 2 "$NUM_VECTORS"); do
    KEY_RAW=$(random_hex 16)
    PLAIN_RAW=$(random_hex 16)

    KEY=$(format_hex "$KEY_RAW")
    PLAIN=$(format_hex "$PLAIN_RAW")

    CIPHER=$("$BIN" enc "$PLAIN" "$KEY")

    echo "${KEY_RAW},${PLAIN_RAW},${CIPHER}" >> "$OUTFILE"
done

echo "Written $NUM_VECTORS vectors to $OUTFILE"
echo "---"

# ── Quick sanity check ────────────────────────────────────────────────────────
echo "[3/3] Sanity check — FIPS 197 Appendix B vector:"
echo "  Key       : $KNOWN_KEY"
echo "  Plaintext : $KNOWN_PLAIN"
echo "  Ciphertext: $KNOWN_CIPHER"

EXPECTED="3925841d02dc09fbdc118597196a0b32"

if [ "$KNOWN_CIPHER" = "$EXPECTED" ]; then
    echo "  Result    : PASS (matches expected $EXPECTED)"
else
    echo "  Result    : FAIL"
    echo "  Expected  : $EXPECTED_FMT"
    echo "  Got       : $KNOWN_CIPHER"
    echo ""
    echo "  Fix your C model before using these vectors for RTL validation."
    exit 1
fi

echo "---"
echo "Done. $OUTFILE is ready for testbench use."
